spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:db;MODE=MYSQL
    password: ''
  profiles:
    include: API-KEY
  messages:
    encoding: UTF-8

logging.level:
  org.hibernate.SQL: debug
