spring:
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
  h2:
    console:
      enabled: 'true'
  messages:
    encoding: UTF-8
  profiles:
    include: API-KEY

logging.level:
  org.hibernate.SQL: debug

jwt:
  secret:
    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA

