spring:
  profiles:
    include: API-KEY, secret, aws
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    encoding: UTF-8

logging.level:
  org.hibernate.SQL: debug
