spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
  profiles:
    include: API-KEY, secret
  messages:
    encoding: UTF-8

logging.level:
  org.hibernate.SQL: debug
