spring:
  profiles:
    include: API-KEY, secret
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
        format_sql: true
  h2:
    console:
      enabled: 'true'
  messages:
    encoding: UTF-8

logging.level:
  org.hibernate.SQL: debug


